name: Test and Coverage

on:
  pull_request:
    branches:
      - main
  push:


jobs:
  test-and-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Run tests
        run: go test -v ./...

      - name: Install test coverage tool
        run: go get github.com/codecov/codecov-action

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: 
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Update coverage badge
        run: |
          COVERAGE_PERCENT=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
          sed -i "s/coverage-[0-9.]\+/coverage-${COVERAGE_PERCENT}/" README.md
